### ISSUE TITLE
Having file names with no spaces upon saving

### ISSUE THREAD

**Issue by biulas** [wlabarron/submit-show#51]
Hello Barron, 

Is is possible to have the files saved without the spaces on the server? 

Reason is - they are in fact playable if one replaces the spaces for % - but to use in Podcast service, URL cannot have those caracters. 

So in stead of saving the file like "Aritst - show name date.mp3" something like "artisit-show-name-date.mp3"

Thanks for the support.

**Comment by wlabarron** [comment]
Hi, that could be possible as an extension of #46. Which podcast service is rejecting the URL? `%20` is valid in URLs so it shouldn't be rejected (and so there's probably a bug there).

**Comment by biulas** [comment]
Hey B, thanks for your feedback.

I'm using Powerpress from Wordpress repository. If I paste a link on the podcast post with the `%20` on the spaces, the plugin cannot access the file. If I take the spaces out and replace for a known character, then the file can be parsed on the plugin.

**Comment by wlabarron** [comment]
Okay, so within this project, I can [add a replacement](https://github.com/wlabarron/submit-show/pull/46/commits/c4c3a2a9deea29fde07e92320053641180c155a7#diff-1f01358ee4e1c740ea08d4435a2d58b568d3c77f330f0e61312be5387c1779d7R339) for show names and presenter names without spaces. I'll try and get that done for the next release (unless I'm beaten to it!) so you'll be able to configure the file name to your liking.

I'd suggest also raising this with the PowerPress plugin developers, since while `%20` in a URL isn't very pretty, it should still be valid (unless there's something I don't understand about how their system works).
